name = "Hypixel-Skyblock-Packwiz"
author = "Emile Loiselle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "694485a87531838c2c1c3c34083124d03e345db8017385f5ab8284a10919c901"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
